import type { Metadata } from 'next'
import { Inter, Roboto, Oswald } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet"></link>

      </head>
      <body  className={inter.className} 
      
      >
        {/* <Navbar/> */}
        <main className='relative overflow-hidden bg-black'>  {children} </main>
       
        <Footer/>
        </body>
    </html>
  )
}
